### ISSUE TITLE
Make rich-text-editor-plugin plugin compatible with OpenJDK 17

### ISSUE THREAD

**Issue by jedfonner** [appian/rich-text-editor-plugin#6]
See https://issues.appian.com/browse/INFRA-24966

**Comment by jedfonner** [comment]
@ddtobiasz FYI

**Comment by ddtobiasz** [comment]
Noted, we got a bunch of these for other plugins too..

**Comment by jedfonner** [comment]
Is there a playbook or cheat sheet on the best way to upgrade?  Is it just changing from `JavaVersion.VERSION_1_8` to `JavaVersion.VERSION_17` in build.gradle?

**Comment by ddtobiasz** [comment]
HA -- so I did what I do best with anything Java-build related and delegated 😉 

I asked CS to update their "plugin template" repo since this affects all plugins, and was going to apply changes to all our plugins after that.

@marcoamador was kind enough to put out [this PR](https://github.com/appianps/ps-plugin-Template/pull/11) -- there's still some discussion open on it, but my plan was to copy that paradigm in this and a few other ones when it's complete.

**Comment by ddtobiasz** [comment]
WAITTTTT a minute -- @marcoamador's first comment in the PR I linked above was that he tested that specific change with this repo! @marcoamador is that something you can push to here as a PR??

**Comment by marcoamador** [comment]
@ddtobiasz yep, can do that. The branch I tested still did not have the latest accessibility changes. I'll merge that into my branch and submit a PR.

The build was fine but we should probably validate the JAR in an env to play it safe.

**Comment by marcoamador** [comment]
@ddtobiasz @jedfonner here it is - https://github.com/appian/rich-text-editor-plugin/pull/7
